version: '3'
services:
  aidb:
    build: ./db
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db/init/:/docker-entrypoint-initdb.d
    container_name: ai_db
  postgres:
    build: ./db
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      #   - ./db/init:/docker-entrypoint-initdb.d
      - ./keycloak/data:/var/lib/postgresql/data
    container_name: idp_db
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    ports:
      - 8085:8080
    depends_on:
      - postgres
    container_name: idp_keycloak
